---
- include: pre_requisite.yml
- include: packages.yml
  when:
  - "vars['xmrig_install_package'] is defined"
  - "vars['xmrig_install_package'] == true"
- include: xmrig_executor.yml
  when:
  - "vars['xmrig_instances'] is defined"
  - "vars['xmrig_instances'] != ''"
