---
- name: Restart xmrig
  systemd:
    name: "{{ hostvars[inventory_hostname]['xmrig_' ~ item.type ~ '_service'] ~
      item.name }}"
    state: "restarted"
  loop: "{{ vars['xmrig_instances'] | flatten(levels=1) }}"
  loop_control:
    label: "{{ 'xmrig-' ~ item.type ~ ': ' ~ item.name }}"
  when:
  - "hostvars[inventory_hostname]['xmrig'] is defined"
  - "hostvars[inventory_hostname]['xmrig'] != ''"
  - "hostvars[inventory_hostname]['xmrig'] |
     json_query(vars['xmrig_restart']) is defined"
  - "hostvars[inventory_hostname]['xmrig'] |
     json_query(vars['xmrig_restart']) == 'true'"
  vars:
    xmrig_restart: "[] | map(&restart || 'false', @) | [0]"
