---
- name: Restart xmrig
  systemd:
    name: "{{ vars['xmrig_service'] ~ item }}"
    state: "restarted"
  with_items: "{{ vars['xmrig_instances'] }}"
  when:
  - "vars['xmrig_restart'] is defined"
  - "vars['xmrig_restart'] == true"
