---
- name: Restart xmrig
  systemd:
    name: "{{ vars['xmrig_service'] ~ item }}"
    state: "restarted"
  loop: "{{ vars['xmrig_instances'] | flatten(levels=1) }}"
  when:
  - "vars['xmrig_restart'] is defined"
  - "vars['xmrig_restart'] == true"
